services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./prisma/db/dev.db:/app/prisma/db/dev.db:rw
    networks:
      - nestjs

networks:
  nestjs:
    driver: bridge